{% set name = "yacman" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e10babf0faa1e77ce35d8d00e6be1aa762aef5db6666db09015ba013a65e5f45

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - attmap >=0.13.0
    - jsonschema >=3.2.0
    - oyaml
    - python >={{ python_min }}
    - pyyaml >=3.13
    - ubiquerg >=0.7.0

test:
  imports:
    - yacman

about:
  home: https://github.com/databio/yacman/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: YAML configuration manager

extra:
  recipe-maintainers:
    - stolarczyk
    - nsheff
