{% set name = "yacman" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53cc5fdf342e0e9f772cfb5079aafb9e3eed6e61d9d5e018dc16873e03742b34

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attmap >=0.12.9
    - oyaml
    - python >=3.6
    - pyyaml >=3.13
    - ubiquerg >=0.6.1
    - jsonschema >=3.2.0

test:
  imports:
    - yacman

about:
  home: https://github.com/databio/yacman/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: YAML configuration manager

extra:
  recipe-maintainers:
    - stolarczyk
