{% set name = "yacman" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 203d8159709c6f2ba7cb2c99c96f0386de3a2d30fc1d26c38226f16d1f8c1b55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml >=5.0
    - ubiquerg >=0.9.1

test:
  imports:
    - yacman

about:
  home: https://github.com/databio/yacman/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: YAML configuration manager

extra:
  recipe-maintainers:
    - stolarczyk
    - nsheff
